//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MusicaLogMDL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Album
    {
        public long Id { get; set; }
        public string Title { get; set; }
        public string Type { get; set; }
        public Nullable<int> Stock { get; set; }
        public string ArtistName { get; set; }
    }
}
